services:
  mysql:
    container_name: brev_db
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: brev
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    container_name: server
    build: ../server
    ports:
      - "5050:5050"
    environment:
      DB_HOST: mysql
      FRONTEND_ORIGIN: http://localhost:5000
    depends_on:
      - mysql
    restart: always
  
  web:
    container_name: web
    build: ../web
    ports:
      - "5000:5000"
    environment:
      VITE_API_BASE_URL: http://localhost:5050/api
    depends_on:
      - server

volumes:
  db-data: